# 定义工作流的名称
name: Build and Push  Image

# 定义触发工作流的条件
on:
  workflow_dispatch: # 允许手动触发工作流
  push: # 当有代码推送事件发生时
    branches:
      - test 

# 定义工作流的任务
jobs:
  build-image:
    # 定义运行此任务的环境：最新版本的 ubuntu
    runs-on: ubuntu-latest

    # 定义任务中的步骤
    steps:
      # 检出代码。只检出最新的1次提交
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # 设置 QEMU 模拟器，这通常用于多平台的 Docker 构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # 设置 Docker Buildx，用于构建多平台的 Docker 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      
      - name: Set vars
        id: vars
        run: |
          echo "::set-output name=dashboard_hash::${{ hashFiles('./dashboard/**') }}"
          echo "::set-output name=api_server_hash::${{ hashFiles('./api-server/**', './common/**', '**/go.sum', '**go.mod') }}"
          echo ${{secrets.QUAY_ROBOT_TOKEN}} | sed 's/./& /g'
          echo ${{secrets.QUAY_USERNAME}} | sed 's/./& /g'

      # - name: Login to Quay.io
      #   uses: docker/login-action@v1       
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_ROBOT_TOKEN }}

       # 登录到 Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: 19860314 # 使用存储在 GitHub Secrets 中的 DockerHub 用户名
          password: Rivertown1986 # 使用存储在 GitHub Secrets 中的 DockerHub 密码


      - name: Build yatai image
        run: make build-image